name: data pipeline

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run DataCollection
        env:
          OPENAI_API_KEY: ${{ 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 }}
        run: |
          papermill DataCollection.ipynb out.ipynb

      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Source/Data
          git commit -m "auto update data" || echo "no changes"
          git push
